pipeline{
    agenet any 
    environment {
        PROJECT_NAME = "MyProject"
        DEPLOY_ENV = "production"
    }
    stages{
        stage('Checkout Code'){
            step{
                git branch:'main',url:'https://github.com/DexterMorgann/Node-Express.git'
            }
        }
        stage('Install Dependencies'){
            steps{
                sh 'npm install'
            }
        }
                stage('Build React App') {
            steps {
                sh '''
                    npm run build
                '''
            }
        }
                stage('Upload to S3') {
            steps {
                sh '''
                    aws s3 sync build/ s3://$S3_BUCKET --delete
                '''
            }
        }


    }
        post {
        success {
            echo " Deployment to S3 Successful!"
        }
        failure {
            echo "Deployment Failed. Check Jenkins Console Output."
        }
    }
}

}
