pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = 'ap-south-1'
        S3_BUCKET = 'jenkins1st-task'
        NODEJS = '/var/lib/jenkins/.nvm/versions/node/v14.21.3/bin'
    }

    stages {

        stage('Checkout Code') {
            steps {
                git(
                    branch: 'main',
                    credentialsId: '7cca05d8-4ab2-4f21-a761-ecda5edf8793',
                    url: 'https://github.com/DexterMorgann/Node-Express.git'
                )
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    export PATH="$NODEJS:$PATH"
                    node -v
                    npm -v
                    npm install
                '''
            }
        }

        stage('Build Project') {
            steps {
                sh '''
                    export PATH="$NODEJS:$PATH"
                    npm run build
                '''
            }
        }

        stage('Upload To S3') {
            steps {
                withAWS(credentials: 'AWS Access key', region: "${AWS_DEFAULT_REGION}") {
                    sh 'aws s3 sync build/ s3://$S3_BUCKET --delete'
                }
            }
        }
    }

    post {
        success { echo "Deployment Successful!" }
        failure { echo "Deployment Failed!" }
    }
}
